# fly.toml app configuration file generated for kanban-adonis-api on 2023-06-18T18:19:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kanban-adonis-api"
primary_region = "jnb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
